apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-216116/pipeline:c4638a0947c17f9c864e2569dfa50a8b098809f6
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
